### ISSUE TITLE
Extend to enable this view/container to have different shapes?

### ISSUE THREAD

**Issue by kunalverma25** [tomasen/WordCloudDemo#1]
Hey @tomasen 
Awesome demo and article! 👏👏
Is it possible for this approach to be scaled to compose of different shapes?
Something like a packed bubble chart sort of?
Would love to see something like that too in SwiftUI, it’s the same case with word cloud as you said no resources and articles on Swift/iOS mostly only on JS.

**Comment by tomasen** [comment]
Thanks.

I think the only thing that needs to be changed for any regular shapes, is the part of the code for checking intersection. Instead of checking if the rectangle is intersected, estimate if the shapes inside the rectangle are intersected.
